//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DraftApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialsView
    {
        public int IdM { get; set; }
        public string Name { get; set; }
        public int IdTM { get; set; }
        public byte[] Image { get; set; }
        public decimal Cost { get; set; }
        public int QuantityStock { get; set; }
        public int MinimumAllowableQuantity { get; set; }
        public int QuantityPackage { get; set; }
        public int IdUM { get; set; }
        public string Description { get; set; }
        public string NameTM { get; set; }
        public string PS { get; set; }
        public string BackgroundColor
        {
            get
            {
                if (QuantityStock < MinimumAllowableQuantity) return "#f19292";
                else if (QuantityStock >= MinimumAllowableQuantity*3) return " #ffba01";
                return "";
            }
        }
    }
}
