//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DraftApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class DraftDatabaseEntities : DbContext
    {
        private static DraftDatabaseEntities _context;
        public static DraftDatabaseEntities GetContext()
        {
            if (_context == null)
                _context = new DraftDatabaseEntities();
            return _context;
        }
        public DraftDatabaseEntities()
            : base("name=DraftDatabaseEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<TypesMaterials> TypesMaterials { get; set; }
        public virtual DbSet<TypesSuppliers> TypesSuppliers { get; set; }
        public virtual DbSet<UnitsMeasurement> UnitsMeasurement { get; set; }
        public virtual DbSet<MaterialsView> MaterialsView { get; set; }
    }
}
